
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CALIB COMMA ID INPUT LPAREN MODULE NUMBER OUTPUT PLACEHOLDER RPAREN SEMICO SPLITprogram : program expr SEMICOprogram : expr SEMICOexpr : INPUT varlist\n    | OUTPUT varlist\n    | PLACEHOLDER varlistexpr : MODULE ID LPAREN NUMBER COMMA NUMBER RPARENexpr : CALIB ID LPAREN varlist RPARENexpr : varlist ASSIGN SPLIT LPAREN ID RPARENexpr : varlist ASSIGN ID LPAREN varlist RPARENvarlist : varlist COMMA IDvarlist : ID'
    
_lr_action_items = {'INPUT':([0,1,11,19,],[3,3,-2,-1,]),'OUTPUT':([0,1,11,19,],[5,5,-2,-1,]),'PLACEHOLDER':([0,1,11,19,],[6,6,-2,-1,]),'MODULE':([0,1,11,19,],[7,7,-2,-1,]),'CALIB':([0,1,11,19,],[9,9,-2,-1,]),'ID':([0,1,3,5,6,7,9,11,13,14,19,24,25,26,],[8,8,8,8,8,17,18,-2,21,22,-1,8,29,8,]),'$end':([1,11,19,],[0,-2,-1,]),'SEMICO':([2,8,10,12,15,16,22,32,33,34,36,],[11,-11,19,-3,-4,-5,-10,-7,-8,-9,-6,]),'ASSIGN':([4,8,22,],[13,-11,-10,]),'COMMA':([4,8,12,15,16,22,27,28,30,],[14,-11,14,14,14,-10,31,14,14,]),'RPAREN':([8,22,28,29,30,35,],[-11,-10,32,33,34,36,]),'SPLIT':([13,],[20,]),'LPAREN':([17,18,20,21,],[23,24,25,26,]),'NUMBER':([23,31,],[27,35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expr':([0,1,],[2,10,]),'varlist':([0,1,3,5,6,24,26,],[4,4,12,15,16,28,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program expr SEMICO','program',3,'p_program_iter','yacc.py',8),
  ('program -> expr SEMICO','program',2,'p_program_end','yacc.py',14),
  ('expr -> INPUT varlist','expr',2,'p_expr_define','yacc.py',19),
  ('expr -> OUTPUT varlist','expr',2,'p_expr_define','yacc.py',20),
  ('expr -> PLACEHOLDER varlist','expr',2,'p_expr_define','yacc.py',21),
  ('expr -> MODULE ID LPAREN NUMBER COMMA NUMBER RPAREN','expr',7,'p_expr_module','yacc.py',26),
  ('expr -> CALIB ID LPAREN varlist RPAREN','expr',5,'p_expr_calib','yacc.py',31),
  ('expr -> varlist ASSIGN SPLIT LPAREN ID RPAREN','expr',6,'p_expr_oper','yacc.py',36),
  ('expr -> varlist ASSIGN ID LPAREN varlist RPAREN','expr',6,'p_expr_assign','yacc.py',41),
  ('varlist -> varlist COMMA ID','varlist',3,'p_varlist_iter','yacc.py',46),
  ('varlist -> ID','varlist',1,'p_varlist_end','yacc.py',52),
]
